### ISSUE TITLE
Bro

### ISSUE THREAD

**Issue by VeiledKernel** [WolfDen133/WFT-OLD#1]
How to break a line in the text

**Comment by BroCrows** [comment]
He said in the description! Use a hashtag(#)

**Comment by VeiledKernel** [comment]
Sorry my bad

**Comment by WolfDen133** [comment]
Sorry for that, ive now added a usage in the description, its also in the form :D

**Comment by VeiledKernel** [comment]
Thanks bro 👍, appreciate it

**Comment by WolfDen133** [comment]
Happy to help, create another issue if you need anything else. :)

**Comment by VeiledKernel** [comment]
Sure, thanks
