### ISSUE TITLE
[Bug] Tags will only work once!

### ISSUE THREAD

**Issue by BroCrows** [WolfDen133/WFT-OLD#10]
**Detailed(ish) Description**
So while just casually testing and using the tags you gave us, I noticed one thing. The tags only updated once, at first I didn't noticed in until I did /ft edit! There I found out that when the tag updated it in fact removed the tag and replaced with with a number.

**Quick Description**
When tags update, they wont update again as tag gets removed.

**Steps to Reproduce**
1. Create a hologram with a tag(i.e. {load})
2. Wait for the hologram to update
3. Do /ft edit and select the hologram you made
4. See a number instead of the tag

Need any more info, just tell me!

**Comment by WolfDen133** [comment]
Hi there, I tried out this bug and cant seem to reproduce it, could you please send some screenshots and I will take a look?

**Comment by BroCrows** [comment]
So I had my server off, but when I turned it on, all the holograms were gone! So found another bug

**Comment by BroCrows** [comment]
And now confusion starts! It is now working for me too!

**Comment by BroCrows** [comment]
![673AA992-0E44-4630-B2CC-E069B5B82ACD](https://user-images.githubusercontent.com/49970753/107857662-5bd47f00-6df5-11eb-9514-003fb241a4cf.jpeg)
Here is the only image I have

**Comment by BroCrows** [comment]
When I was adding load to the hologram, as seen where I put players has '1' instead of '{online_players}' and tps has '20' instead of '{tps}'

**Comment by WolfDen133** [comment]
Interesting it always returns the tag for me, and when the texts disappear, usually its a bug with the onJoin function so /ft reload might fix it, if not just create it again, it should be fixed now anyway.

**Comment by WolfDen133** [comment]
[!see](https://i.imgur.com/VA54yEc.png) so im not to sure

**Comment by BroCrows** [comment]
> Interesting it always returns the tag for me, and when the texts disappear, usually its a bug with the onJoin function so /ft reload might fix it, if not just create it again, it should be fixed now anyway.

There isnt an /ft reload

**Comment by BroCrows** [comment]
#11 Talk in here instead
