### ISSUE TITLE
[Bug] Hologram get removed sometimes

### ISSUE THREAD

**Issue by BroCrows** [WolfDen133/WFT-OLD#11]
So the hologram doesn't get removed, it's your database fault! You need to add which world the hologram is in to keep the hologram in that world not lost in the code!

**Quick Description**
Add which level the hologram is in to the database!

**Comment by WolfDen133** [comment]
I just added the command with the name sub aswell

**Comment by BroCrows** [comment]
Ok

**Comment by WolfDen133** [comment]
I also fixed the FTS spawning on the 00 of the block so now they spawn in there correct positions

**Comment by BroCrows** [comment]
Yeah it fixed it
