### ISSUE TITLE
[Bug] Duplicate holograms!

### ISSUE THREAD

**Issue by BroCrows** [WolfDen133/WFT-OLD#12]
So when I finished editing my holograms in the configs(because of limit in game) I noticed that my holograms where duplicated!
![8EFBF547-A5D8-4208-A651-03DD181CB684](https://user-images.githubusercontent.com/49970753/107890804-7e8f9200-6ee0-11eb-8aaf-f0fd9341fb57.png)
![78E62DE3-D6AB-488B-9A42-4EB234B33B15](https://user-images.githubusercontent.com/49970753/107890805-7fc0bf00-6ee0-11eb-87f4-420e82de4ba5.png)
![A5B4945C-C907-4EEB-873B-F1BD9C065ACB](https://user-images.githubusercontent.com/49970753/107890806-80595580-6ee0-11eb-9529-8ca69bbfd798.png)

**Comment by WolfDen133** [comment]
Hmm, very interesting, ill take a look at the code, may I have your discord so you can test some release builds for bugs.

**Comment by BroCrows** [comment]
ZZWILLIAMXX#9825

**Comment by WolfDen133** [comment]
This issue is fixed in the latest patch
