### ISSUE TITLE
[Suggestion] Tags

### ISSUE THREAD

**Issue by BroCrows** [WolfDen133/WFT-OLD#2]
Probably a stretch, and its ok if you dont do this! But could you possibly add tags for plugins? You know how ScoreHud has tags, do stuff like that. Maybe tags like...
{top_faction.x} - Shows top faction(Any factions plugin)
{top_killer.x} - Shows top killer(KDR)
I suggested this for Texter, but he declined(Which I kind of understand for some reason)

**Comment by WolfDen133** [comment]
Hi there, currently the floating texts are static based, so once you set the text it will be like that forever (unless you edit it), but im sure I can work in a feature like this, would you like to like to see an update timer slider so you can choose how often they update if I do add this feature?

**Comment by WolfDen133** [comment]
Edit. sorry for my terrible English, I think I'm retarded.

**Comment by BroCrows** [comment]
Yeah I was thinking of an update timer before I read the update timer part.

**Comment by WolfDen133** [comment]
In the next release(1.3) I will add the tags functionality, please let me know a list of common plugins you would like to see added.

**Comment by BroCrows** [comment]
Ok!
# Plugins I Use
OnlineTime - {onlinetime.total.x} 

# Other Plugins
KDR - {kills.x} {kdr.kdr.x}
BravoClan - {clan.lvl.x} & {clan.kills.x}
FactionsPro/FactionsPE/PiggyFactions - {faction}
Skyblock/RedSkyblock - {is.rank.x} & or {is.value.x}
Prisons - {prisons.rank.x}
Bedwars - {bedwars.kills.x} & {bedwars.wins.x}
Skywars - {skywars.kills.x} & {skywars.wins.x}
EconomyAPI - {economy.top.x}
BetterVoting/PocketVote - {topvoter.x} (kinda useless as for the plugin, TopVoter)
Also sorry for late reply!

**Comment by BroCrows** [comment]
All of the plugins above are released, none of them are in dev

**Comment by WolfDen133** [comment]
So, the floating texts are global, witch means these things should be true for all of the players online, i will be converting them to packets soon, but for now i will be getting the top of all the results. Please reopen this in [Ideas](https://github.com/WolfDen133/WFT/discussions)
