### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by theogboby** [WolfDen133/WFT-OLD#24]
I add some floating text and after i rejoin to server i get an internal server error.

![PicsArt_04-04-11 59 30](https://user-images.githubusercontent.com/81933505/113522567-d7ef7580-95a1-11eb-88ec-967a2c9cb645.jpg)

**Comment by WolfDen133** [comment]
Ah yes, this happens because the world the ft is added on was deleted but the ft is still trying to join, resulting in a error, I will upload a patch shortly.

**Comment by WolfDen133** [comment]
FIXED
