### ISSUE TITLE
Suggestions for WFT

### ISSUE THREAD

**Issue by TheBalkanDev** [WolfDen133/WFT-OLD#25]
Good evening,

First I must say, its the best floating text/hologram Plugin for PMMP.

But I have suggestions.

1. More Placeholders
2. Plz add Holograms, that only can made in a Plot (MyPlot Support).
I mean that players can make their own holograms on there Plots.
Command example /plotholo or /p holo 
Please add ;)

**Comment by WolfDen133** [comment]
Hi there, more place holders and leader-boards will be coming in the future, but the my plot support might be a little harder to do, don't fear I feel I will be able to do this, but could take some time, I am currently working on better Tags/Placeholders so stay tuned.

**Comment by TheBalkanDev** [comment]
Okay, thanks for replying.
