### ISSUE TITLE
API 4

### ISSUE THREAD

**Issue by TheBalkanDev** [WolfDen133/WFT-OLD#26]
Hey,

Can you make this plug-in compatible with the API 4?
And can you make it MyPlot compatible, I’ve codet my very own and buggy floating text Plugin but it is terrible.
Can you maybe add it.

And Can you speak German?

**Comment by WolfDen133** [comment]
Hi there, good to hear from you, unfortunately I cannot speak German, Im not to sure on how the api for pmmp 4 has changed as I only use pmmp 3, I have had lot's of requests for extra tags but I am currently unable to work on the plugin, and not to sure if I will update it in future, you can dm me on discord about custom plugins if you wish my discord is ฬ๏ɭŦ๔єภ133#4974, Have fun.
