### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ItzFel** [WolfDen133/WFT-OLD#9]
![IMG_20210213_052547](https://user-images.githubusercontent.com/62336632/107824216-0fb91880-6dbc-11eb-8d0a-b72e93f62548.jpg)

If i join my server i got internal server error.

**Comment by BroCrows** [comment]
Hmm I don't seem to have this error. It seems like the text entity cannot be created in an unloaded chunk. Since I don't know code that well, can't help you so sorry!

**Comment by ItzFel** [comment]
even though the world I spawned is already loaded, do all worlds have to load?

**Comment by BroCrows** [comment]
Hmm maybe! Try to use [this](https://poggit.pmmp.io/p/LoadAllWorlds/1.1.2) plugin!

**Comment by ItzFel** [comment]
My server is Skyblock, so it is impossible for me to load all the worlds and it will lag my server

**Comment by WolfDen133** [comment]
Hi yes, sorry for the delay, I am currently working on the 1.3.1 bug fix patch so just wait and your problems will be fixed soon.

**Comment by ItzFel** [comment]
ok thanks!

**Comment by WolfDen133** [comment]
This bug is now (hopefully) fixed, thanks for the report!
